targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          exclude:
            - example/**
      envied_generator:envied:
        enabled: true
        generate_for:
          exclude:
            - example/**
      riverpod_generator:
        enabled: true
        generate_for:
          exclude:
            - example/**
      freezed:
        enabled: true
        generate_for:
          exclude:
            - example/**
    

