name: riverpod_infinite_scroll_pagination
description: An infinite scroll pagination using Riverpod (Lazy loading pages as the user scrolls to the end of the list).
version: 3.0.0
homepage: https://github.com/hafees/riverpod_infinite_scroll
repository: https://github.com/hafees/riverpod_infinite_scroll
issue_tracker: https://github.com/hafees/riverpod_infinite_scroll/issues

topics:
  - riverpod
  - pagination
  - scrolling-pagination
  - infinite-scroll-pagination

environment:
  sdk: ">=3.8.0 <4.0.0"

  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^3.2.0
  json_serializable: ^6.7.1
  very_good_analysis: ^9.0.0
  riverpod_annotation: ^3.0.0-dev.17
  test: ^1.26.2
  riverpod_generator: ^3.0.0-dev.17
  envied_generator: ^1.2.0
  mocktail: ^1.0.1
  custom_lint:
  riverpod_lint: ^3.0.0-dev.17

flutter:
